### ISSUE TITLE
No direct method <init>(Ljava/io/Reader;)V in class Lorg/json/JSONTokener; 

### ISSUE THREAD

**Issue by gkj17** [stleary/JSON-java#602]
````
  Process: pnkj.android.life, PID: 12315
    java.lang.NoSuchMethodError: No direct method <init>(Ljava/io/Reader;)V in class Lorg/json/JSONTokener; or its super classes (declaration of 'org.json.JSONTokener' appears in /system/framework/core-libart.jar)
        at org.json.XMLTokener.<init>(XMLTokener.java:57)
        at org.json.XML.toJSONObject(XML.java:651)
        at org.json.XML.toJSONObject(XML.java:709)
        at org.json.XML.toJSONObject(XML.java:578)
````

this is the error code:
        val xmlJSONObj: JSONObject = XML.toJSONObject(myXML)

myXML is :

````
<expEN>
    <list>
        <wordClass>n.</wordClass>
        <item>
            <explain>the chance to speak</explain>
            <sentence>\"let him have his say\"</sentence>
        </item>
    </list>
    <list>
        <wordClass>v.</wordClass>
        <item>
            <explain>express in words</explain>
            <synonyms>state,tell</synonyms>
        </item>
        <item>
            <explain>report or maintain</explain>
            <sentence>\"The registrar says that I owe the school money\"</sentence>
            <synonyms>allege,aver</synonyms>
        </item>
        <item>
            <explain>express a supposition</explain>
            <sentence>\"Let us say that he did not tell the truth\"; \" Let's say you had a lot of
                money--what would you do?\"
            </sentence>
            <synonyms>suppose</synonyms>
        </item>
        <item>
            <explain>have or contain a certain wording or form</explain>
            <sentence>\"What does the law say?\"</sentence>
            <synonyms>read</synonyms>
        </item>
        <item>
            <explain>state as one's opinion or judgement; declare</explain>
            <sentence>\"I say let's forget this whole business\"</sentence>
        </item>
        <item>
            <explain>utter aloud</explain>
        </item>
        <item>
            <explain>give instructions to or direct somebody to do something with authority
            </explain>
            <synonyms>order,tell,enjoin</synonyms>
        </item>
        <item>
            <explain>speak, pronounce, or utter in a certain way</explain>
            <sentence>\"I cannot say `zip wire'\"</sentence>
            <synonyms>pronounce,articulate,enounce,sound out,enunciate</synonyms>
        </item>
        <item>
            <explain>recite or repeat a fixed text</explain>
        </item>
        <item>
            <explain>communicate or express nonverbally</explain>
            <sentence>\"What does this painting say?\"; \" Did his face say anything about how he
                felt?\"
            </sentence>
        </item>
        <item>
            <explain>indicate</explain>
            <sentence>\"The clock says noon\"</sentence>
        </item>
    </list>
</expEN>

````

**Comment by stleary** [comment]
@gkj17 
[https://github.com/stleary/JSON-java/wiki/JSON-Java-for-Android-developers](https://github.com/stleary/JSON-java/wiki/JSON-Java-for-Android-developers)

Does this Wiki page offer any insight?
By the way, what version of Android are you writing this code for?
