### ISSUE TITLE
I have a little problem

### ISSUE THREAD

**Issue by MagFra** [stleary/JSON-java#624]
Can you please help me sort this out?
I keep getting a error massage.

```
import org.json.JSONArray;
import org.json.JSONObject;

public class Main {

    public static void main(String[] args) {
        String jsonStr = "{ \"Number1\" : 123.456 , \"Number2\" : [ 223.456 , 323.456 ] }";
        JSONObject json = new JSONObject(jsonStr);
        Float number1 = json.getFloat("Number1");
        System.out.println(json);
        JSONArray jsonArr = json.getJSONArray("Number2");
        System.out.println(jsonArr);
        System.out.println(number1);
        Float number2 = jsonArr.getFloat(0);
        System.out.println(number2);
        Float number3 = jsonArr.getFloat(1);
        System.out.println(number3);
    }
}
```

**Comment by stleary** [comment]
Please post the errors you are seeing. Your code compiles and executes correctly for me.

**Comment by MagFra** [comment]
Hmm...   Ok...
This simple program was created to illustrate a problem I got in a much bigger project I'm been working on, on and off for some time. The problem occurred when I, after taking a long pause, got back to it the other day. Immediately  the IntelliJ IDEA goes in to update all sorts of things. (Both it self, plug inns and project dependencies. (I use Maven to handle dependencies.))
Now the simple example here does show the exact same problem. So I will supply the entire console response and my Pom file.

Console:
```F:\Downloads\Java\JDK14\bin\java.exe "-javaagent:F:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.1\lib\idea_rt.jar=63471:F:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.1\bin" -Dfile.encoding=UTF-8 -classpath F:\Dokument\Java\TestJ\target\classes;C:\Users\Lasse\.m2\repository\junit\junit\4.13.2\junit-4.13.2.jar;C:\Users\Lasse\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;C:\Users\Lasse\.m2\repository\org\json\json\20210307\json-20210307.jar;C:\Users\Lasse\.m2\repository\org\jetbrains\annotations\22.0.0\annotations-22.0.0.jar Main
{"Number2":[223.456,323.456],"Number1":123.456}
[223.456,323.456]
123.456
Exception in thread "main" java.lang.ClassCastException: class java.math.BigDecimal cannot be cast to class java.lang.Float (java.math.BigDecimal and java.lang.Float are in module java.base of loader 'bootstrap')
	at org.json.JSONArray.getFloat(JSONArray.java:329)
	at Main.main(Main.java:14)

Process finished with exit code 1```

Pom:
```<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>TestJ</artifactId>
    <version>1.0-SNAPSHOT</version>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>14</source>
                    <target>14</target>
                </configuration>
            </plugin>
        </plugins>
    </build>


    <dependencies>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.8.1</version>
            <scope>test</scope>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.json/json -->
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20210307</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains</groupId>
            <artifactId>annotations</artifactId>
            <version>22.0.0</version>
            <scope>compile</scope>
        </dependency>


    </dependencies>


</project>```

**Comment by stleary** [comment]
Not sure. What Java version are you using?

**Comment by MagFra** [comment]
openjdk-14 java version "14.0.1"
SDK default (14 - Switch expressions)

**Comment by MagFra** [comment]
I am thinking I might switch to a later version, sort of soon-ich. I would like to evaluate the impact first.

**Comment by stleary** [comment]
Presuming this issue to be resolved since no activity has been logged recently. But feel free to post here if there are still problems.

**Comment by johnjaylward** [comment]
this was actually fixed in a more recent commit than the submitter was using:
https://github.com/stleary/JSON-java/commit/75894086e59d3b6ec23e35825c468fde5618366b

Users version: org.json 20210307 (2021-03-07)
Fixed in 2021-04-27

@stleary , it looks like we need a new release published.

**Comment by stleary** [comment]
@johnjaylward Thanks for catching this, will cut a new release in the next week.

**Comment by stleary** [comment]
Marking this completed with release 20211205
